export const initialIdeas = [
  {
    nome: 'Academia Para Plantas Ansiosas',
    categoria: 'App',
    empolgacao: 3,
    motivo: 'O algoritmo confundiu crescimento saudavel com crise existencial botanica.',
    survival_percentage: 18,
    cause_of_death_summary: 'O algoritmo confundiu crescimento saudavel com crise existencial botanica.',
    ai_verdict: 'A proposta prometia treinos personalizados para samambaias inseguras. Morreu quando descobriram que a maioria das plantas preferia apenas agua e silencio.',
  },
  {
    nome: 'Rede Social Para Pessoas Que Digitam E Apagam',
    categoria: 'Rede Social',
    empolgacao: 4,
    motivo: 'Usuarios escreviam manifestos que nunca seriam publicados.',
    survival_percentage: 27,
    cause_of_death_summary: 'Usuarios escreviam manifestos que nunca seriam publicados.',
    ai_verdict: 'A ideia tinha potencial, mas ninguem postava nada. Ainda assim, todos passavam horas ensaiando uma versao melhor de si mesmos.',
  },
  {
    nome: 'Delivery De Motivacao As 3 Da Manha',
    categoria: 'Servico',
    empolgacao: 4,
    motivo: 'A autoestima nao cabia no prazo de entrega.',
    survival_percentage: 22,
    cause_of_death_summary: 'A autoestima nao cabia no prazo de entrega.',
    ai_verdict: 'O servico prometia frases motivacionais emergenciais. Nao resistiu ao primeiro cliente pedindo proposito de vida com cupom de desconto.',
  },
  {
    nome: 'Aplicativo Que Julga Seu Carrinho De Compras',
    categoria: 'App',
    empolgacao: 5,
    motivo: 'O sistema confundiu consumo impulsivo com pedido de socorro.',
    survival_percentage: 31,
    cause_of_death_summary: 'O sistema confundiu consumo impulsivo com pedido de socorro.',
    ai_verdict: 'A IA analisava compras impulsivas e emitia pareceres. O projeto foi arquivado apos sugerir terapia para quem comprou uma luminaria em formato de pato.',
  },
  {
    nome: 'Curso Online De Como Terminar Cursos Online',
    categoria: 'Curso',
    empolgacao: 5,
    motivo: 'Os alunos pararam no modulo sobre nao parar.',
    survival_percentage: 12,
    cause_of_death_summary: 'Os alunos pararam no modulo sobre nao parar.',
    ai_verdict: 'A curadoria considera esta uma obra-prima da ironia educacional. Poucas ideias representaram tao bem seu proprio problema.',
  },
  {
    nome: 'Startup De Aluguel De Personalidade',
    categoria: 'Startup',
    empolgacao: 4,
    motivo: 'Tres usuarios alugaram a mesma aura misteriosa.',
    survival_percentage: 19,
    cause_of_death_summary: 'Tres usuarios alugaram a mesma aura misteriosa.',
    ai_verdict: 'Prometia resolver inseguranca social sob demanda. Nao sobreviveu a reuniao de branding, embora tenha deixado um logo bastante confiante.',
  },
  {
    nome: 'Agenda Que Grita Quando Voce Procrastina',
    categoria: 'Produtividade',
    empolgacao: 3,
    motivo: 'As notificacoes foram silenciadas no primeiro dia.',
    survival_percentage: 25,
    cause_of_death_summary: 'As notificacoes foram silenciadas no primeiro dia.',
    ai_verdict: 'A agenda tinha uma missao nobre: constranger a procrastinacao. Infelizmente, subestimou a habilidade humana de ignorar alertas.',
  },
  {
    nome: 'Museu Dos Prints Que Nunca Foram Enviados',
    categoria: 'Memorial Digital',
    empolgacao: 4,
    motivo: 'Algumas evidencias nasceram para permanecer soterradas.',
    survival_percentage: 16,
    cause_of_death_summary: 'Algumas evidencias nasceram para permanecer soterradas.',
    ai_verdict: 'O projeto tinha enorme valor historico, mas a curadoria concluiu que algumas evidencias devem permanecer na pasta chamada nao mandar jamais.',
  },
  {
    nome: 'App De Mapa Astral Para Reunioes Corporativas',
    categoria: 'Corporativo Mistico',
    empolgacao: 3,
    motivo: 'O financeiro pediu evidencias em Mercurio retrogrado.',
    survival_percentage: 21,
    cause_of_death_summary: 'O financeiro pediu evidencias em Mercurio retrogrado.',
    ai_verdict: 'A ideia prometia prever conflitos em reunioes com base nos signos dos participantes. Morreu quando o financeiro pediu evidencias.',
  },
  {
    nome: 'IA Que Escolhe Sua Proxima Obsessao',
    categoria: 'IA',
    empolgacao: 5,
    motivo: 'Recomendava novos projetos para quem nao terminou os antigos.',
    survival_percentage: 34,
    cause_of_death_summary: 'Recomendava novos projetos para quem nao terminou os antigos.',
    ai_verdict: 'A IA compreendeu perfeitamente seu publico-alvo e, por isso mesmo, tornou-se perigosa demais para continuar operando.',
  },
];
